name: Run All Tests

on:
  push:
    branches:
      - "**"

concurrency:
  group: continuous-integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  issues: write
  checks: write
  pull-requests: write

jobs:
  pytest_unit_and_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache poetry install
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-2.0.0

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Python Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: .venv
          key: "pydeps-${{ hashFiles('**/poetry.lock') }}"

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry install --no-interaction

      - name: Run unit tests
        run: poetry run python -m pytest -m unit

      - name: Run integration tests
        run: poetry run python -m pytest -m integration
